### ISSUE TITLE
Upgrade to Yarn 3

### ISSUE THREAD

**Issue by antoine-duchenet** [zenika-open-source/oss.zenika.com#429]
From https://github.com/zenika-open-source/oss.zenika.com/issues/421#issuecomment-1745154161 .

**Comment by jeanphibaconnais** [comment]
We find a solution to our problem of yarn (https://github.com/zenika-open-source/oss.zenika.com/pull/428). 
I will look this yarn upgrade after checking all PR in this repo.
Thanks for your time 🙏
